language: node_js
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
before_install:
  - npm install -g greenkeeper-lockfile
install: npm install # npm ci won't work with greenkeeper pull
before_script: greenkeeper-lockfile-update
script:
  - npm run test
after_script: greenkeeper-lockfile-upload
services:
  - mongodb
